# Definition der Ressourcen für die S3-Bucket-Erstellung
Resources:
  myStaticWebsiteHostingBucket:
    Type: 'AWS::S3::Bucket'   # S3-Bucket-Typ
    Properties:
      BucketName: trg-bucket-tb  # Name des S3-Buckets
      WebsiteConfiguration:
        IndexDocument: index.html   # Standardindexdokument für die statische Website
        ErrorDocument: error.html   # Fehlerdokument für die Website

      # Ownership Controls sind definiert
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter   # Regel für Ownership, in diesem Fall "ObjectWriter"

      # Einstellungen für den öffentlichen Zugriff auf den Bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false   # Blockieren von öffentlichen ACLs (Access Control Lists)
        BlockPublicPolicy: false   # Blockieren von öffentlichen Richtlinien
        IgnorePublicAcls: false   # Ignorieren von öffentlichen ACLs
        RestrictPublicBuckets: false   # Beschränken öffentlicher Buckets 

  # Definition einer Bucket-Richtlinie (Policy) für öffentlichen Lesezugriff
  myStaticWebsiteHostingBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref myStaticWebsiteHostingBucket   # Bezieht sich auf den zuvor erstellten S3-Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects   # Eine eindeutige Kennung für die Richtlinienanweisung
            Effect: Allow   # Erlauben
            Principal: '*'   # Jeder (alle Benutzer)
            Action: 's3:GetObject'   # Berechtigung zum Abrufen von Objekten
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref myStaticWebsiteHostingBucket
                - '/*'   # Ressource: Alle Objekte im Bucket

# Definition einer Output-Variablen für die URL der statischen Website
Outputs:
  outputWebsiteURL:
    Value: !GetAtt 
      - myStaticWebsiteHostingBucket
      - WebsiteURL   # Gibt die URL der statischen Website zurück
    Description: Static website URL   # Beschreibung der Output-Variable
